version: "3.3"

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
          
  db:
    container_name: postgres
    environment:
        - POSTGRES_PASSWORD=postPassword
    ports:
        - '5432:5432'
    image: run